services:
  bun:
    container_name: bun
    build:
      context: ./bun
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./bun:/app
    ports:
      - "3007:3007"
    networks:
      - internal

  node:
    container_name: node
    build:
      context: ./node
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./node:/app
    ports:
      - "3005:3005"
    networks:
      - internal

  golang:
    container_name: golang
    build:
      context: ./golang
    restart: always
    ports: 
      - "3001:3001"

  # cpp:
  #   container_name: cpp-app
  #   build:
  #     context: ./cpp
  #     dockerfile: dev.Dockerfile
  #   restart: always
  #   volumes:
  #     - ./cpp:/app
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - internal
  #   command: ["/app/cpp_server"]

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
